### ISSUE TITLE
echo -e doesn't work on Mac when using bash

### ISSUE THREAD

**Issue by smenzer** [Bhupesh-V/dotman#1]
**Describe the bug**
The command `echo -e "Some text"` writes `-e Some text` to the screen.

**To Reproduce**
1. Run dotman

**Expected behavior**
The `-e` is not included in the output

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.5
 - Bash Version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

**Additional context**
Consider using `printf` instead

**Comment by Bhupesh-V** [comment]
Hi @smenzer :wave: Thanks for reporting this.
Would fix this in the next release

**Comment by Bhupesh-V** [comment]
@all-contributors please add @smenzer  for bug

**Comment by Bhupesh-V** [comment]
Fixed in [0.2.0](https://github.com/Bhupesh-V/dotman/releases/tag/v0.2.0)
