### ISSUE TITLE
initial_setup not passing DOT_REPO to clone_dotrepo

### ISSUE THREAD

**Issue by fpitters** [Bhupesh-V/dotman#3]
**Describe the bug**
initial_setup not passing DOT_REPO to clone_dotrepo, missing the $.

**To Reproduce**
Use initial_setup flow

**Expected behavior**
Repo is cloned

**Actual**
Getting:
fatal: repository 'DOT_REPO' does not exist
[❌] DOT_REPO Unavailable. Exiting

PD: Really nice, dotfiles manager :raised_hands: Thanks!

**Comment by Bhupesh-V** [comment]
@all-contributors please add @fpitters  for bug

**Comment by Bhupesh-V** [comment]
@all-contributors please add @fpitters  for bug
